---
- name: Install wireguard
  include_tasks: install.yml
  when:
    - wireguard_install

- name: Configure wireguard server
  include_tasks: cli-config-server.yml
  when:
    - wireguard_configure == "server"

- name: Configure wireguard client
  include_tasks: cli-config-client.yml
  when:
    - wireguard_configure == "client"
